### ISSUE TITLE
Uncaught AssertionError: missing path

### ISSUE THREAD

**Issue by cgdobre** [Statwolf/statwolf-console-plugin#1]
[Enter steps to reproduce below:]

1. CTRL+J

**Atom Version**: 1.8.0
**System**: "openSUSE Leap
**Thrown From**: [statwolf-console-plugin](https://github.com/Statwolf/statwolf-console-plugin) package, v0.0.25

### Stack Trace

Uncaught AssertionError: missing path

```
At assert.js:89

AssertionError: missing path
    at Module.require (module.js:364:3)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at CommandView.module.exports.CommandView.initialize (/home/cgdobre/.atom/packages/statwolf-console-plugin/lib/statwolf-command-console.coffee:35:22)
    at CommandView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new CommandView (/home/cgdobre/.atom/packages/statwolf-console-plugin/lib/statwolf-command-console.coffee:16:3)
    at StatwolfConsolePluginView.module.exports.StatwolfConsolePluginView.createCommandView (/home/cgdobre/.atom/packages/statwolf-console-plugin/lib/statwolf-console-plugin-view.coffee:32:25)
    at StatwolfConsolePluginView.module.exports.StatwolfConsolePluginView.castCommand (/home/cgdobre/.atom/packages/statwolf-console-plugin/lib/statwolf-console-plugin-view.coffee:43:6)
    at atom-workspace.atom.commands.add.statwolf-console-plugin:evalToBuffer (/home/cgdobre/.atom/packages/statwolf-console-plugin/lib/statwolf-console-plugin-view.coffee:24:62)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:03.1.0 editor:join-lines (atom-text-editor.editor.is-focused)
     -0:00.5.0 statwolf-console-plugin:evalToBuffer (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
build-dockerfile, v1.0.1
language-docker, v1.1.6
linter-docker, v0.1.2
statwolf-console-plugin, v0.0.25

# Dev
No dev packages
```

**Comment by b3by** [comment]
Hello @cgdobre, I can see your issue depends on the fact that this is a package that belongs to a bigger suite of packages we're currently using internally in our company! I'm afraid it could be of little help to your needs.

Sorry about that!
